services:
  - type: web
    name: zklear-payment-system
    env: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /api/system-info
    envVars:
      - key: RUST_LOG
        value: info
      - key: RUST_BACKTRACE
        value: 1
    buildCommand: ./build-render.sh
    startCommand: ./start.sh 